builds:
  - env: 
      - CGO_ENABLED=0
    dir: cmd/gogios/
    goos:
      - linux
      - windows
      - darwin
      - freebsd
      - openbsd
      - netbsd
gitea_urls:
  api: https://codeberg.org/api/v1
  download: https://codeberg.org
archives:
  - format: tar.gz
env_files:
  gitea_token: ~/.gitea_token
