version: '3'

tasks:
  build:
    cmds:
      - go build -o gogios cmd/gogios/main.go
  check:
    cmds:
      - go vet **/*.go
      - golangci-lint run
  lint-install:
    cmds:
      - go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
