version: '3'

tasks:
  build:
    cmds:
      - go build -o gogios cmd/gogios/main.go
  dev:
    deps: ["vet", "lint"]
    cmds:
      - go build -race -o gogios cmd/gogios/main.go
  vet:
    cmds:
      - go vet **/*.go
  lint:
    cmds:
      - golangci-lint run
  lint-install:
    cmds:
      - go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
